# Generated by Django 3.2.16 on 2022-11-29 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_visual_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visual',
            name='userid',
        ),
        migrations.AddField(
            model_name='dataload',
            name='userid',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
